# Generated by Django 5.0.6 on 2026-03-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_stock_prediction_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='predicted_price_30d',
            new_name='predicted_price_1d',
        ),
    ]
